moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.7.0
project:
  name: solo-relayer-service
  mode: personal
  description: ''
  created_at: '2026-01-22 16:54:40'
  optimized: false
  locale: ko
  language: generic
  template_version: 1.7.0
